name: Deploy Web

on:
  push:
    branches:
      - master
    paths:
      - "packages/**"
      - ".github/workflows/deploy-web.yml"

jobs:
  deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build Docs
        working-directory: ./packages/docs
        run: yarn build

      - name: Build web
        working-directory: ./packages/web
        run: yarn generate

      - name: Build storybook
        working-directory: ./packages/web
        run: yarn build-storybook

      - name: Move docs inside web build
        working-directory: ./packages/web
        run: |
          mkdir ./dist/docs
          mv ../docs/build/* ./dist/docs

      - name: Move storybook inside web build
        working-directory: ./packages/web
        run: |
          mv ./storybook ./dist

      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: ./packages/web/dist
